import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import Sidbar from "../components/sidbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "layout Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen w-screen`}
      >
        <div className="relative overflow-hidden bg-darckBg text-tGrayAll flex flex-col h-screen">
          <div className="sticky">
            <Header />
          </div>
          <div className="grid grid-cols-12">
            <Sidbar />
            <div className="col-span-9 h-screen">
              {children}
            </div>
          </div>
          <div className="fixed bottom-0 w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
